function Song () {
    music.setTempo(250)
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.playTone(349, music.beat(BeatFraction.Whole))
    color(0, 0, 1)
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(659, music.beat(BeatFraction.Double))
    music.playTone(523, music.beat(BeatFraction.Double))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    color(0, 1, 0)
    music.playTone(523, music.beat(BeatFraction.Double))
    music.playTone(494, music.beat(BeatFraction.Double))
    music.playTone(494, music.beat(BeatFraction.Double))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(330, music.beat(BeatFraction.Whole))
    color(1, 0, 0)
    music.playTone(349, music.beat(BeatFraction.Double))
    music.playTone(587, music.beat(BeatFraction.Double))
    music.playTone(494, music.beat(BeatFraction.Double))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    color(0, 1, 0)
    music.playTone(440, music.beat(BeatFraction.Double))
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.playTone(349, music.beat(BeatFraction.Whole))
    color(0, 1, 1)
    music.playTone(392, music.beat(BeatFraction.Double))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Double))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    color(1, 0, 1)
    music.playTone(440, music.beat(BeatFraction.Double))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Double))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    color(0, 0, 1)
    music.playTone(392, music.beat(BeatFraction.Double))
    color(1, 0, 0)
    music.playTone(698, music.beat(BeatFraction.Double))
    color(0, 1, 0)
    music.playTone(659, music.beat(BeatFraction.Double))
    color(0, 0, 1)
    music.playTone(587, music.beat(BeatFraction.Double))
    color(1, 1, 1)
    music.playTone(523, music.beat(BeatFraction.Breve))
    color(0, 0, 0)
    music.rest(music.beat(BeatFraction.Breve))
    music.setVolume(100)
    color(0, 0, 1)
    music.playTone(523, music.beat(BeatFraction.Double))
    color(0, 0, 0)
    music.rest(music.beat(BeatFraction.Whole))
    color(0, 1, 1)
    music.playTone(523, music.beat(BeatFraction.Whole))
    color(1, 1, 1)
    music.playTone(659, music.beat(BeatFraction.Double))
    color(0, 0, 1)
    music.playTone(523, music.beat(BeatFraction.Double))
    color(0, 1, 1)
    music.playTone(587, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Breve))
    color(0, 0, 1)
    music.setVolume(150)
    music.playTone(587, music.beat(BeatFraction.Double))
    color(0, 0, 0)
    music.rest(music.beat(BeatFraction.Whole))
    color(0, 1, 1)
    music.playTone(587, music.beat(BeatFraction.Whole))
    color(1, 1, 1)
    music.playTone(698, music.beat(BeatFraction.Double))
    color(0, 0, 1)
    music.playTone(587, music.beat(BeatFraction.Double))
    color(0, 1, 1)
    music.playTone(659, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Breve))
    music.setVolume(200)
    color(0, 0, 1)
    music.playTone(659, music.beat(BeatFraction.Double))
    color(0, 0, 0)
    music.rest(music.beat(BeatFraction.Whole))
    color(0, 1, 1)
    music.playTone(659, music.beat(BeatFraction.Whole))
    color(1, 1, 1)
    music.playTone(784, music.beat(BeatFraction.Double))
    color(0, 0, 1)
    music.playTone(659, music.beat(BeatFraction.Double))
    color(0, 1, 1)
    music.playTone(698, music.beat(BeatFraction.Double))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Double))
    music.setVolume(100)
    color(0, 0, 0)
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.setVolume(150)
    color(0, 0, 1)
    music.playTone(392, music.beat(BeatFraction.Breve))
    music.setVolume(200)
    color(0, 1, 1)
    music.playTone(494, music.beat(BeatFraction.Breve))
    music.setVolume(255)
    color(1, 1, 1)
    music.playTone(523, music.beat(BeatFraction.Breve))
    color(0, 0, 0)
    music.rest(music.beat(BeatFraction.Breve))
    music.setVolume(175)
}
function color (blue: number, white: number, green: number) {
    pins.digitalWritePin(DigitalPin.P0, blue)
    pins.digitalWritePin(DigitalPin.P1, white)
    pins.digitalWritePin(DigitalPin.P2, green)
}
input.onGesture(Gesture.Shake, function () {
    shake = 1
})
let shake = 0
music.setBuiltInSpeakerEnabled(true)
music.setVolume(175)
shake = 0
basic.forever(function () {
    if (shake == 0) {
        for (let index = 0; index <= 600; index++) {
            pins.analogWritePin(AnalogPin.P0, index)
            pins.analogWritePin(AnalogPin.P1, 600 - index)
            basic.pause(1)
        }
        pins.analogWritePin(AnalogPin.P0, 600)
        pins.digitalWritePin(DigitalPin.P1, 0)
        basic.pause(200)
        for (let index = 0; index <= 600; index++) {
            pins.analogWritePin(AnalogPin.P0, 600 - index)
            pins.analogWritePin(AnalogPin.P1, index)
            basic.pause(1)
        }
        pins.digitalWritePin(DigitalPin.P0, 0)
        pins.analogWritePin(AnalogPin.P1, 600)
        basic.pause(200)
    } else {
        pins.digitalWritePin(DigitalPin.P0, 0)
        pins.digitalWritePin(DigitalPin.P1, 0)
        Song()
        shake = 0
        for (let index = 0; index <= 600; index++) {
            pins.analogWritePin(AnalogPin.P1, index)
            basic.pause(1)
        }
        basic.pause(200)
    }
})
